### ISSUE TITLE
context.getUser() returns undefined after logging in

### ISSUE THREAD

**Issue by jimmy-e** [ericmakesapps/graphql-passport#20]
**Problem:**
`context.getUser()` is not working despite logging in.

**To Reproduce:**
*Note:* Code was written using [these articles](https://jkettmann.com/authentication-and-authorization-with-graphql-and-passport/) and [this repo](https://github.com/jkettmann/authentication-with-graphql-passport-and-react) as resources.

1. [Clone this repo/branch](https://github.com/jimmy-e/mybord-server/tree/passport_testing_2)
2. Run `yarn`
3. Run `yarn build:dev`
4. In a second terminal, run `yarn run:dev`.
5. Login (note that the terminal does show us that the user is authenticated and `context.getUser` works).
```
mutation {
  login(email: "maurice@moss.com", password: "abcdefg") {
    user {
      id
      firstName
      lastName
      email
    }
  }
}
```

terminal response:
```
--- login response ---
isAuthenticated: true
isUnauthenticated: false
getUser: [object Object]
```

6. Run the `currentUser` query (note that the terminal shows us that the user is not authenticated, despite logging in, and that `context.getUser` returns undefined):
```
query{
  currentUser{
    id
  }
}
```

terminal response:
```
--- currentUser response ---
isAuthenticated: false
isUnauthenticated: true
getUser: undefined
```

**Main code used:**
*index.ts:*
```js
import { ApolloServer } from 'apollo-server-express';
import express from 'express';
import http from 'http';
import passport from 'passport';
import session from 'express-session';
import uuid from 'uuid/v4';
import { GraphQLLocalStrategy, buildContext } from 'graphql-passport';
import Users from './users';
import resolvers from './resolvers';
import typeDefs from './typeDefs';

passport.serializeUser((user, done) => {
  // @ts-ignore
  done(null, user.id);
});

passport.deserializeUser((id, done) => {
  const users = Users.getUsers();
  const matchingUser = users.find((user) => user.id === id);
  done(null, matchingUser);
});

passport.use(
  new GraphQLLocalStrategy((email, password, done) => {
    const users = Users.getUsers();
    const matchingUser = users.find((user) => email === user.email && password === user.password);
    const error = matchingUser ? null : new Error('no matching user');
    done(error, matchingUser);
  }),
);

const server = new ApolloServer({
  context: ({ req, res }) => buildContext({ req, res, Users }),
  resolvers,
  typeDefs,
});

export default server;

// Adds express as middleware to our server.
const app = express();
app.use(session({
  // cookie: { secure: true }, // cookie must be sent via https
  genid: (request) => uuid(), // generates a session ID
  resave: false,
  saveUninitialized: false,
  secret: 'bad secret', // secret that is needed to sign the cookie
}));

app.use(passport.initialize());
app.use(passport.session());

server.applyMiddleware({ app });

const PORT = 4000;

// We create an http server from our apollo server.
const httpServer = http.createServer(app);
server.installSubscriptionHandlers(httpServer);

// We run our http server.
httpServer.listen(PORT, () => {
  console.log(`Server ready at http://localhost:${PORT}${server.graphqlPath}`);
  console.log(`Subscriptions ready at ws://localhost:${PORT}${server.subscriptionsPath}`);
});

// Using webpack's hot module replacement, if needed.
if (module.hot) {
  module.hot.accept();
  module.hot.dispose(() => server.stop());
}
```

*resolvers.ts:*
```js
const resolvers = {
  Query: {
    currentUser: (parent, args, context) => {
      console.log('--- currentUser response ---');
      console.log(`isAuthenticated: ${context.isAuthenticated()}`);
      console.log(`isUnauthenticated: ${context.isUnauthenticated()}`);
      console.log(`getUser: ${context.getUser()}`);
      return context.getUser();
    },
  },
  Mutation: {
    login: async (parent, { email, password }, context) => {
      const { user } = await context.authenticate('graphql-local', { email, password });
      context.login(user);

      console.log('--- login response ---');
      console.log(`isAuthenticated: ${context.isAuthenticated()}`);
      console.log(`isUnauthenticated: ${context.isUnauthenticated()}`);
      console.log(`getUser: ${context.getUser()}`);

      return { user };
    },
  },
};

export default resolvers;
```

**Comment by jkettmann** [comment]
Hi Jimmy, thanks for this issue. I checked your repository and everything seems to be fine. Actually, when I run the project the login is working for me. Can you check if the `connect.sid` cookie is set after login? If it's currently set please delete it first.

One thing that comes to my mind is the playground settings. In the repo you mentioned the playground settings are defined [inside the code](https://github.com/jkettmann/authentication-with-graphql-passport-and-react/blob/master/api/index.js#L50) as

```
playground: {
    settings: {
      'request.credentials': 'same-origin',
    },
  },
``` 

You can also do this manually by opening the settings via the gear symbol in the right top in the playground and add following line:

```
"request.credentials": "same-origin"
```

Let me know if this worked

**Comment by gforge** [comment]
The login() is also an async call that uses a callback - you need to promisify it to be sure that the authentication has been implemented.

**Comment by jimmy-e** [comment]
> Hi Jimmy, thanks for this issue. I checked your repository and everything seems to be fine. Actually, when I run the project the login is working for me. Can you check if the `connect.sid` cookie is set after login? If it's currently set please delete it first.
> 
> One thing that comes to my mind is the playground settings. In the repo you mentioned the playground settings are defined [inside the code](https://github.com/jkettmann/authentication-with-graphql-passport-and-react/blob/master/api/index.js#L50) as
> 
> ```
> playground: {
>   settings: {
>     'request.credentials': 'same-origin',
>   },
> },
> ```
> 
> You can also do this manually by opening the settings via the gear symbol in the right top in the playground and add following line:
> 
> ```
> "request.credentials": "same-origin"
> ```
> 
> Let me know if this worked

Thanks @jkettmann , changing the playground settings solved the problem!

Curious, as a front end dev who is just know learning the back-end via graphql, what do these playground settings exactly mean?

Also, how would I check the `connect.sid`?

Thanks and keep up the great work!

P.S.: [This article](https://jkettmann.com/authentication-and-authorization-with-graphql-and-passport/) has the `currentUser` resolver using `context.user`. In the following article, that resolver however should change to be `context.getUser()`, something that was confusing to me at first when reading and might help to clarify.

**Comment by jimmy-e** [comment]
> The login() is also an async call that uses a callback - you need to promisify it to be sure that the authentication has been implemented.

Thanks @gforge , can you clarify / expand? My login mutation is using async / await. Is there something else I should be doing?

**Comment by gforge** [comment]
I'm not sure why as `login()` should just add the user to the context but it is defined as a [callback function](https://github.com/jaredhanson/passport/blob/master/lib/sessionmanager.js). I've therefore added a `Promise` around it in order to make sure it resolves:

```ts
    async login(
      _: unknown,
      { name, password }: { name: string; password: string },
      { authenticate, login }: MyContext,
    ) {
      const { user } = await authenticate('graphql-local', { username: name, password });
      await new Promise(resolve => login(user, () => resolve()));
      return !!user;
    },
```

@jkettmann: We could probably add a `loginAsync` in the `buildContext`, possibly using `utils.promisify` - the old callback syntax of passport feels somewhat outdated and cumbersome. What do you think? I could do a PR once we're done with the current ones.

**Comment by gforge** [comment]
Sorry, just realized that we're already returning a promise from login. This makes me wonder though if the package should sidestep the regular passport behavior. It may be better to use callbacks for `login` and then have an `loginAsync` - one way would be to deprecate the `login` for a few versions in favor for `loginAsync` and then change. Anyway, I've modified the server test code to simply:

```ts
    async login(
      _: unknown,
      { name, password }: { name: string; password: string },
      { authenticate, login }: MyContext,
    ) {
      const { user } = await authenticate('graphql-local', { username: name, password });
      await login(user);
      return !!user;
    },
```

**Comment by jkettmann** [comment]
@jimmy-e Thanks for pointing me to the error in the article. The API changed at some point and I missed to update the code samples.

As for the async login: you have these two lines in the login resolver

```
const { user } = await context.authenticate('graphql-local', { email, password });
context.login(user);
```

It should be `await context.login(user);` as @gforge mentioned correctly. This is also wrong in the article. Sorry for the confusion.

**Comment by jkettmann** [comment]
@gforge I don't think it's necessary to change the API. Since `authenticate` is promisified we should be consistent here. The `login` function is throwing an error in case [the serialization doesn't work](https://github.com/jaredhanson/passport/blob/master/lib/sessionmanager.js#L16)

**Comment by gforge** [comment]
@jkettmann - yeah, I guess you're right. My instinct was that the login will probably be queued to be handled after the failing contexts as they happen in @jimmy-e's example code. Anyway, hopefully the typings should help users to correctly call the functions.

**Comment by calebneuf** [comment]
Sorry to reopen this issue, however, I'm facing the same concern. Login details are returned correctly, but deserializeUser is never called, and therefore, user is undefined.

**Comment by ericbf** [comment]
Can you post an example of your code and what you are seeing?

**Comment by ericbf** [comment]
If you still have issues, can you create a new issue? Thanks!
