### ISSUE TITLE
Issues with apollo server 3

### ISSUE THREAD

**Issue by tombannister1** [ericmakesapps/graphql-passport#67]
Hi, When logging in i get a returned user however the current user resolver is returning
undefined.

` currentUser: (parent, args, context) => { console.log(context.getUser()); return context.getUser()},`

Wondering if you had any idea why or if you were working on an update for this?

I have rolled back to apollo server 2 which works. However with it not being the latest version i would like to try avoid this,

**Comment by khoi-fish** [comment]
@tombannister1 does this happen on every request? I notice that it only happens to me after the server restarts, after which, I have to clear my cookies, then re-login

**Comment by ericbf** [comment]
Closing this as stale, but we can revisit if it is still an issue.
